### ISSUE TITLE
Beachgrass not spawning in Terraforged world type.

### ISSUE THREAD

**Issue by V4m4cher0n** [minecraftabnormals/Upgrade-Aquatic#126]
This is quite self-explanatory. Beachgrass does not spawn in Terraforged world types from the mod (Terraforged), however, sea rockets, pickerel weed, and, uh...I forget the name of those flowers that have the cool animation, anyway yeah, those 3 plants spawn. 

Can provide a log if needed.

**Comment by SmellyModder** [comment]
Won't fix, was investigating this with another user getting the same issue, due to how Terraforged handles its beaches terrain, specifically the height, it makes it very hard, near impossible, for the conditions for generating beachgrass to be met.

Terraforged beaches tend to be a lot more flat, which is the main cause.
