### ISSUE TITLE
Thrasher's sometimes swim up air

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Upgrade-Aquatic#168]
https://gyazo.com/304f5d9a89cd7fdb8edaed16ef6314c1

**Comment by SmellyModder** [comment]
This is an odd issue and can't really be fixed since it's a Vanilla issue.
The Thrasher in the clip is trying to navigate up the water stream to get away from the lava, but the Thrasher is big and has a bit of swaying motion when it swims so it falls out of the stream, but it keeps trying to swim up the stream. 
A similar effect can be reproduced with Dolphins, but the Dolphins are less prone to mess up when swimming up the stream since they're smaller and have more 'stable' motion when swimming.
