### ISSUE TITLE
[REPOST] `upgrade_aquatic:bedrolls` tag, and for other colored blocks for easier datapack customization

### ISSUE THREAD

**Issue by thelegitdolt** [minecraftabnormals/Upgrade-Aquatic#393]
Reopened from https://github.com/team-abnormals/upgrade-aquatic/issues/351. Vanilla seems to have tags for a lot of colored block, including carpets, wools, beds, candles, glass panes, glass and terracotta. Though it is probably unnecessary in the base game, it can be very convenient for a lot of modpack creators (for example-- a recipe using a bedroll to craft some other items), and having to create tag for colored blocks can lead to a lot of duplication of effort

**Comment by bageldotjpg** [comment]
While I will probably add this tag eventually anyway, I'm not sure why you reposted this, because I had already closed the issue prior and GitHub has a re-open issue feature.

As mentioned before, tags are added when they are used, this tag would be unused. Also, glass panes and glass don't have tags. If a modpack needs the tag for whatever reason, like for a recipe, they are already creating the recipe, they can create the tag too very simply.
