### ISSUE TITLE
Driftwood Generation Config

### ISSUE THREAD

**Issue by virohe** [minecraftabnormals/Upgrade-Aquatic#410]
I'm trying to build a modpack with a focus on sea-faring. In play-testing, driftwood chunks were becoming quite the nuisance, so the ability to toggle driftwood generation would be helpful from a pack-design point of view.

**Comment by davidjjung** [comment]
If you're in 1.20.1, worldgen features (especially from a pack design perspective) should be modified via datapack. https://github.com/team-abnormals/upgrade-aquatic/tree/1.20.x/src/generated/resources/data/upgrade_aquatic/tags/worldgen/biome/has_feature on this page it shows the biome tags in which upgrade aquatic's features generate.

this includes four driftwood biome tags that, when made empty (aka just the "values" bracket with no biomes/biome tags inside), should more than cover your needs. from a code perspective, it's preferable to replace this data with packs rather than making it a config option, as worldgen features are now generated before runtime and are now much more readily accessed from a data perspective
